// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Blob;
@class BlobHeader;
@class BlobHeader_Builder;
@class Blob_Builder;

@interface FileformatRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Blob : PBGeneratedMessage {
@private
  BOOL hasRawSize_:1;
  BOOL hasRaw_:1;
  BOOL hasZlibData_:1;
  BOOL hasLzmaData_:1;
  BOOL hasObsoleteBzip2Data_:1;
  int32_t rawSize;
  NSData* raw;
  NSData* zlibData;
  NSData* lzmaData;
  NSData* obsoleteBzip2Data;
}
- (BOOL) hasRaw;
- (BOOL) hasRawSize;
- (BOOL) hasZlibData;
- (BOOL) hasLzmaData;
- (BOOL) hasObsoleteBzip2Data;
@property (readonly, retain) NSData* raw;
@property (readonly) int32_t rawSize;
@property (readonly, retain) NSData* zlibData;
@property (readonly, retain) NSData* lzmaData;
@property (readonly, retain) NSData* obsoleteBzip2Data;

+ (Blob*) defaultInstance;
- (Blob*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Blob_Builder*) builder;
+ (Blob_Builder*) builder;
+ (Blob_Builder*) builderWithPrototype:(Blob*) prototype;

+ (Blob*) parseFromData:(NSData*) data;
+ (Blob*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Blob*) parseFromInputStream:(NSInputStream*) input;
+ (Blob*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Blob*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Blob*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Blob_Builder : PBGeneratedMessage_Builder {
@private
  Blob* result;
}

- (Blob*) defaultInstance;

- (Blob_Builder*) clear;
- (Blob_Builder*) clone;

- (Blob*) build;
- (Blob*) buildPartial;

- (Blob_Builder*) mergeFrom:(Blob*) other;
- (Blob_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Blob_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRaw;
- (NSData*) raw;
- (Blob_Builder*) setRaw:(NSData*) value;
- (Blob_Builder*) clearRaw;

- (BOOL) hasRawSize;
- (int32_t) rawSize;
- (Blob_Builder*) setRawSize:(int32_t) value;
- (Blob_Builder*) clearRawSize;

- (BOOL) hasZlibData;
- (NSData*) zlibData;
- (Blob_Builder*) setZlibData:(NSData*) value;
- (Blob_Builder*) clearZlibData;

- (BOOL) hasLzmaData;
- (NSData*) lzmaData;
- (Blob_Builder*) setLzmaData:(NSData*) value;
- (Blob_Builder*) clearLzmaData;

- (BOOL) hasObsoleteBzip2Data;
- (NSData*) obsoleteBzip2Data;
- (Blob_Builder*) setObsoleteBzip2Data:(NSData*) value;
- (Blob_Builder*) clearObsoleteBzip2Data;
@end

@interface BlobHeader : PBGeneratedMessage {
@private
  BOOL hasDatasize_:1;
  BOOL hasType_:1;
  BOOL hasIndexdata_:1;
  int32_t datasize;
  NSString* type;
  NSData* indexdata;
}
- (BOOL) hasType;
- (BOOL) hasIndexdata;
- (BOOL) hasDatasize;
@property (readonly, retain) NSString* type;
@property (readonly, retain) NSData* indexdata;
@property (readonly) int32_t datasize;

+ (BlobHeader*) defaultInstance;
- (BlobHeader*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BlobHeader_Builder*) builder;
+ (BlobHeader_Builder*) builder;
+ (BlobHeader_Builder*) builderWithPrototype:(BlobHeader*) prototype;

+ (BlobHeader*) parseFromData:(NSData*) data;
+ (BlobHeader*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BlobHeader*) parseFromInputStream:(NSInputStream*) input;
+ (BlobHeader*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BlobHeader*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BlobHeader*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BlobHeader_Builder : PBGeneratedMessage_Builder {
@private
  BlobHeader* result;
}

- (BlobHeader*) defaultInstance;

- (BlobHeader_Builder*) clear;
- (BlobHeader_Builder*) clone;

- (BlobHeader*) build;
- (BlobHeader*) buildPartial;

- (BlobHeader_Builder*) mergeFrom:(BlobHeader*) other;
- (BlobHeader_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BlobHeader_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (NSString*) type;
- (BlobHeader_Builder*) setType:(NSString*) value;
- (BlobHeader_Builder*) clearType;

- (BOOL) hasIndexdata;
- (NSData*) indexdata;
- (BlobHeader_Builder*) setIndexdata:(NSData*) value;
- (BlobHeader_Builder*) clearIndexdata;

- (BOOL) hasDatasize;
- (int32_t) datasize;
- (BlobHeader_Builder*) setDatasize:(int32_t) value;
- (BlobHeader_Builder*) clearDatasize;
@end

