// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class ChangeSet;
@class ChangeSet_Builder;
@class DenseInfo;
@class DenseInfo_Builder;
@class DenseNodes;
@class DenseNodes_Builder;
@class HeaderBBox;
@class HeaderBBox_Builder;
@class HeaderBlock;
@class HeaderBlock_Builder;
@class Info;
@class Info_Builder;
@class Node;
@class Node_Builder;
@class PrimitiveBlock;
@class PrimitiveBlock_Builder;
@class PrimitiveGroup;
@class PrimitiveGroup_Builder;
@class Relation;
@class Relation_Builder;
@class StringTable;
@class StringTable_Builder;
@class Way;
@class Way_Builder;
typedef enum {
  Relation_MemberTypeNode = 0,
  Relation_MemberTypeWay = 1,
  Relation_MemberTypeRelation = 2,
} Relation_MemberType;

BOOL Relation_MemberTypeIsValidValue(Relation_MemberType value);


@interface OsmformatRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface HeaderBlock : PBGeneratedMessage {
@private
  BOOL hasWritingprogram_:1;
  BOOL hasSource_:1;
  BOOL hasBbox_:1;
  NSString* writingprogram;
  NSString* source;
  HeaderBBox* bbox;
  NSMutableArray* mutableRequiredFeaturesList;
  NSMutableArray* mutableOptionalFeaturesList;
}
- (BOOL) hasBbox;
- (BOOL) hasWritingprogram;
- (BOOL) hasSource;
@property (readonly, retain) HeaderBBox* bbox;
@property (readonly, retain) NSString* writingprogram;
@property (readonly, retain) NSString* source;
- (NSArray*) requiredFeaturesList;
- (NSString*) requiredFeaturesAtIndex:(int32_t) index;
- (NSArray*) optionalFeaturesList;
- (NSString*) optionalFeaturesAtIndex:(int32_t) index;

+ (HeaderBlock*) defaultInstance;
- (HeaderBlock*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HeaderBlock_Builder*) builder;
+ (HeaderBlock_Builder*) builder;
+ (HeaderBlock_Builder*) builderWithPrototype:(HeaderBlock*) prototype;

+ (HeaderBlock*) parseFromData:(NSData*) data;
+ (HeaderBlock*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HeaderBlock*) parseFromInputStream:(NSInputStream*) input;
+ (HeaderBlock*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HeaderBlock*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HeaderBlock*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HeaderBlock_Builder : PBGeneratedMessage_Builder {
@private
  HeaderBlock* result;
}

- (HeaderBlock*) defaultInstance;

- (HeaderBlock_Builder*) clear;
- (HeaderBlock_Builder*) clone;

- (HeaderBlock*) build;
- (HeaderBlock*) buildPartial;

- (HeaderBlock_Builder*) mergeFrom:(HeaderBlock*) other;
- (HeaderBlock_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HeaderBlock_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBbox;
- (HeaderBBox*) bbox;
- (HeaderBlock_Builder*) setBbox:(HeaderBBox*) value;
- (HeaderBlock_Builder*) setBboxBuilder:(HeaderBBox_Builder*) builderForValue;
- (HeaderBlock_Builder*) mergeBbox:(HeaderBBox*) value;
- (HeaderBlock_Builder*) clearBbox;

- (NSArray*) requiredFeaturesList;
- (NSString*) requiredFeaturesAtIndex:(int32_t) index;
- (HeaderBlock_Builder*) replaceRequiredFeaturesAtIndex:(int32_t) index with:(NSString*) value;
- (HeaderBlock_Builder*) addRequiredFeatures:(NSString*) value;
- (HeaderBlock_Builder*) addAllRequiredFeatures:(NSArray*) values;
- (HeaderBlock_Builder*) clearRequiredFeaturesList;

- (NSArray*) optionalFeaturesList;
- (NSString*) optionalFeaturesAtIndex:(int32_t) index;
- (HeaderBlock_Builder*) replaceOptionalFeaturesAtIndex:(int32_t) index with:(NSString*) value;
- (HeaderBlock_Builder*) addOptionalFeatures:(NSString*) value;
- (HeaderBlock_Builder*) addAllOptionalFeatures:(NSArray*) values;
- (HeaderBlock_Builder*) clearOptionalFeaturesList;

- (BOOL) hasWritingprogram;
- (NSString*) writingprogram;
- (HeaderBlock_Builder*) setWritingprogram:(NSString*) value;
- (HeaderBlock_Builder*) clearWritingprogram;

- (BOOL) hasSource;
- (NSString*) source;
- (HeaderBlock_Builder*) setSource:(NSString*) value;
- (HeaderBlock_Builder*) clearSource;
@end

@interface HeaderBBox : PBGeneratedMessage {
@private
  BOOL hasLeft_:1;
  BOOL hasRight_:1;
  BOOL hasTop_:1;
  BOOL hasBottom_:1;
  int64_t left;
  int64_t right;
  int64_t top;
  int64_t bottom;
}
- (BOOL) hasLeft;
- (BOOL) hasRight;
- (BOOL) hasTop;
- (BOOL) hasBottom;
@property (readonly) int64_t left;
@property (readonly) int64_t right;
@property (readonly) int64_t top;
@property (readonly) int64_t bottom;

+ (HeaderBBox*) defaultInstance;
- (HeaderBBox*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HeaderBBox_Builder*) builder;
+ (HeaderBBox_Builder*) builder;
+ (HeaderBBox_Builder*) builderWithPrototype:(HeaderBBox*) prototype;

+ (HeaderBBox*) parseFromData:(NSData*) data;
+ (HeaderBBox*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HeaderBBox*) parseFromInputStream:(NSInputStream*) input;
+ (HeaderBBox*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HeaderBBox*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HeaderBBox*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HeaderBBox_Builder : PBGeneratedMessage_Builder {
@private
  HeaderBBox* result;
}

- (HeaderBBox*) defaultInstance;

- (HeaderBBox_Builder*) clear;
- (HeaderBBox_Builder*) clone;

- (HeaderBBox*) build;
- (HeaderBBox*) buildPartial;

- (HeaderBBox_Builder*) mergeFrom:(HeaderBBox*) other;
- (HeaderBBox_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HeaderBBox_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLeft;
- (int64_t) left;
- (HeaderBBox_Builder*) setLeft:(int64_t) value;
- (HeaderBBox_Builder*) clearLeft;

- (BOOL) hasRight;
- (int64_t) right;
- (HeaderBBox_Builder*) setRight:(int64_t) value;
- (HeaderBBox_Builder*) clearRight;

- (BOOL) hasTop;
- (int64_t) top;
- (HeaderBBox_Builder*) setTop:(int64_t) value;
- (HeaderBBox_Builder*) clearTop;

- (BOOL) hasBottom;
- (int64_t) bottom;
- (HeaderBBox_Builder*) setBottom:(int64_t) value;
- (HeaderBBox_Builder*) clearBottom;
@end

@interface PrimitiveBlock : PBGeneratedMessage {
@private
  BOOL hasLatOffset_:1;
  BOOL hasLonOffset_:1;
  BOOL hasGranularity_:1;
  BOOL hasDateGranularity_:1;
  BOOL hasStringtable_:1;
  int64_t latOffset;
  int64_t lonOffset;
  int32_t granularity;
  int32_t dateGranularity;
  StringTable* stringtable;
  NSMutableArray* mutablePrimitivegroupList;
}
- (BOOL) hasStringtable;
- (BOOL) hasGranularity;
- (BOOL) hasLatOffset;
- (BOOL) hasLonOffset;
- (BOOL) hasDateGranularity;
@property (readonly, retain) StringTable* stringtable;
@property (readonly) int32_t granularity;
@property (readonly) int64_t latOffset;
@property (readonly) int64_t lonOffset;
@property (readonly) int32_t dateGranularity;
- (NSArray*) primitivegroupList;
- (PrimitiveGroup*) primitivegroupAtIndex:(int32_t) index;

+ (PrimitiveBlock*) defaultInstance;
- (PrimitiveBlock*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PrimitiveBlock_Builder*) builder;
+ (PrimitiveBlock_Builder*) builder;
+ (PrimitiveBlock_Builder*) builderWithPrototype:(PrimitiveBlock*) prototype;

+ (PrimitiveBlock*) parseFromData:(NSData*) data;
+ (PrimitiveBlock*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PrimitiveBlock*) parseFromInputStream:(NSInputStream*) input;
+ (PrimitiveBlock*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PrimitiveBlock*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PrimitiveBlock*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PrimitiveBlock_Builder : PBGeneratedMessage_Builder {
@private
  PrimitiveBlock* result;
}

- (PrimitiveBlock*) defaultInstance;

- (PrimitiveBlock_Builder*) clear;
- (PrimitiveBlock_Builder*) clone;

- (PrimitiveBlock*) build;
- (PrimitiveBlock*) buildPartial;

- (PrimitiveBlock_Builder*) mergeFrom:(PrimitiveBlock*) other;
- (PrimitiveBlock_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PrimitiveBlock_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStringtable;
- (StringTable*) stringtable;
- (PrimitiveBlock_Builder*) setStringtable:(StringTable*) value;
- (PrimitiveBlock_Builder*) setStringtableBuilder:(StringTable_Builder*) builderForValue;
- (PrimitiveBlock_Builder*) mergeStringtable:(StringTable*) value;
- (PrimitiveBlock_Builder*) clearStringtable;

- (NSArray*) primitivegroupList;
- (PrimitiveGroup*) primitivegroupAtIndex:(int32_t) index;
- (PrimitiveBlock_Builder*) replacePrimitivegroupAtIndex:(int32_t) index with:(PrimitiveGroup*) value;
- (PrimitiveBlock_Builder*) addPrimitivegroup:(PrimitiveGroup*) value;
- (PrimitiveBlock_Builder*) addAllPrimitivegroup:(NSArray*) values;
- (PrimitiveBlock_Builder*) clearPrimitivegroupList;

- (BOOL) hasGranularity;
- (int32_t) granularity;
- (PrimitiveBlock_Builder*) setGranularity:(int32_t) value;
- (PrimitiveBlock_Builder*) clearGranularity;

- (BOOL) hasLatOffset;
- (int64_t) latOffset;
- (PrimitiveBlock_Builder*) setLatOffset:(int64_t) value;
- (PrimitiveBlock_Builder*) clearLatOffset;

- (BOOL) hasLonOffset;
- (int64_t) lonOffset;
- (PrimitiveBlock_Builder*) setLonOffset:(int64_t) value;
- (PrimitiveBlock_Builder*) clearLonOffset;

- (BOOL) hasDateGranularity;
- (int32_t) dateGranularity;
- (PrimitiveBlock_Builder*) setDateGranularity:(int32_t) value;
- (PrimitiveBlock_Builder*) clearDateGranularity;
@end

@interface PrimitiveGroup : PBGeneratedMessage {
@private
  BOOL hasDense_:1;
  DenseNodes* dense;
  NSMutableArray* mutableNodesList;
  NSMutableArray* mutableWaysList;
  NSMutableArray* mutableRelationsList;
  NSMutableArray* mutableChangesetsList;
}
- (BOOL) hasDense;
@property (readonly, retain) DenseNodes* dense;
- (NSArray*) nodesList;
- (Node*) nodesAtIndex:(int32_t) index;
- (NSArray*) waysList;
- (Way*) waysAtIndex:(int32_t) index;
- (NSArray*) relationsList;
- (Relation*) relationsAtIndex:(int32_t) index;
- (NSArray*) changesetsList;
- (ChangeSet*) changesetsAtIndex:(int32_t) index;

+ (PrimitiveGroup*) defaultInstance;
- (PrimitiveGroup*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PrimitiveGroup_Builder*) builder;
+ (PrimitiveGroup_Builder*) builder;
+ (PrimitiveGroup_Builder*) builderWithPrototype:(PrimitiveGroup*) prototype;

+ (PrimitiveGroup*) parseFromData:(NSData*) data;
+ (PrimitiveGroup*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PrimitiveGroup*) parseFromInputStream:(NSInputStream*) input;
+ (PrimitiveGroup*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PrimitiveGroup*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PrimitiveGroup*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PrimitiveGroup_Builder : PBGeneratedMessage_Builder {
@private
  PrimitiveGroup* result;
}

- (PrimitiveGroup*) defaultInstance;

- (PrimitiveGroup_Builder*) clear;
- (PrimitiveGroup_Builder*) clone;

- (PrimitiveGroup*) build;
- (PrimitiveGroup*) buildPartial;

- (PrimitiveGroup_Builder*) mergeFrom:(PrimitiveGroup*) other;
- (PrimitiveGroup_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PrimitiveGroup_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) nodesList;
- (Node*) nodesAtIndex:(int32_t) index;
- (PrimitiveGroup_Builder*) replaceNodesAtIndex:(int32_t) index with:(Node*) value;
- (PrimitiveGroup_Builder*) addNodes:(Node*) value;
- (PrimitiveGroup_Builder*) addAllNodes:(NSArray*) values;
- (PrimitiveGroup_Builder*) clearNodesList;

- (BOOL) hasDense;
- (DenseNodes*) dense;
- (PrimitiveGroup_Builder*) setDense:(DenseNodes*) value;
- (PrimitiveGroup_Builder*) setDenseBuilder:(DenseNodes_Builder*) builderForValue;
- (PrimitiveGroup_Builder*) mergeDense:(DenseNodes*) value;
- (PrimitiveGroup_Builder*) clearDense;

- (NSArray*) waysList;
- (Way*) waysAtIndex:(int32_t) index;
- (PrimitiveGroup_Builder*) replaceWaysAtIndex:(int32_t) index with:(Way*) value;
- (PrimitiveGroup_Builder*) addWays:(Way*) value;
- (PrimitiveGroup_Builder*) addAllWays:(NSArray*) values;
- (PrimitiveGroup_Builder*) clearWaysList;

- (NSArray*) relationsList;
- (Relation*) relationsAtIndex:(int32_t) index;
- (PrimitiveGroup_Builder*) replaceRelationsAtIndex:(int32_t) index with:(Relation*) value;
- (PrimitiveGroup_Builder*) addRelations:(Relation*) value;
- (PrimitiveGroup_Builder*) addAllRelations:(NSArray*) values;
- (PrimitiveGroup_Builder*) clearRelationsList;

- (NSArray*) changesetsList;
- (ChangeSet*) changesetsAtIndex:(int32_t) index;
- (PrimitiveGroup_Builder*) replaceChangesetsAtIndex:(int32_t) index with:(ChangeSet*) value;
- (PrimitiveGroup_Builder*) addChangesets:(ChangeSet*) value;
- (PrimitiveGroup_Builder*) addAllChangesets:(NSArray*) values;
- (PrimitiveGroup_Builder*) clearChangesetsList;
@end

@interface StringTable : PBGeneratedMessage {
@private
  NSMutableArray* mutableSList;
}
- (NSArray*) sList;
- (NSData*) sAtIndex:(int32_t) index;

+ (StringTable*) defaultInstance;
- (StringTable*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StringTable_Builder*) builder;
+ (StringTable_Builder*) builder;
+ (StringTable_Builder*) builderWithPrototype:(StringTable*) prototype;

+ (StringTable*) parseFromData:(NSData*) data;
+ (StringTable*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StringTable*) parseFromInputStream:(NSInputStream*) input;
+ (StringTable*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StringTable*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StringTable*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StringTable_Builder : PBGeneratedMessage_Builder {
@private
  StringTable* result;
}

- (StringTable*) defaultInstance;

- (StringTable_Builder*) clear;
- (StringTable_Builder*) clone;

- (StringTable*) build;
- (StringTable*) buildPartial;

- (StringTable_Builder*) mergeFrom:(StringTable*) other;
- (StringTable_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StringTable_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) sList;
- (NSData*) sAtIndex:(int32_t) index;
- (StringTable_Builder*) replaceSAtIndex:(int32_t) index with:(NSData*) value;
- (StringTable_Builder*) addS:(NSData*) value;
- (StringTable_Builder*) addAllS:(NSArray*) values;
- (StringTable_Builder*) clearSList;
@end

@interface Info : PBGeneratedMessage {
@private
  BOOL hasVisible_:1;
  BOOL hasTimestamp_:1;
  BOOL hasChangeset_:1;
  BOOL hasVersion_:1;
  BOOL hasUid_:1;
  BOOL hasUserSid_:1;
  BOOL visible_:1;
  int64_t timestamp;
  int64_t changeset;
  int32_t version;
  int32_t uid;
  int32_t userSid;
}
- (BOOL) hasVersion;
- (BOOL) hasTimestamp;
- (BOOL) hasChangeset;
- (BOOL) hasUid;
- (BOOL) hasUserSid;
- (BOOL) hasVisible;
@property (readonly) int32_t version;
@property (readonly) int64_t timestamp;
@property (readonly) int64_t changeset;
@property (readonly) int32_t uid;
@property (readonly) int32_t userSid;
- (BOOL) visible;

+ (Info*) defaultInstance;
- (Info*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Info_Builder*) builder;
+ (Info_Builder*) builder;
+ (Info_Builder*) builderWithPrototype:(Info*) prototype;

+ (Info*) parseFromData:(NSData*) data;
+ (Info*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Info*) parseFromInputStream:(NSInputStream*) input;
+ (Info*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Info*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Info*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Info_Builder : PBGeneratedMessage_Builder {
@private
  Info* result;
}

- (Info*) defaultInstance;

- (Info_Builder*) clear;
- (Info_Builder*) clone;

- (Info*) build;
- (Info*) buildPartial;

- (Info_Builder*) mergeFrom:(Info*) other;
- (Info_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Info_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersion;
- (int32_t) version;
- (Info_Builder*) setVersion:(int32_t) value;
- (Info_Builder*) clearVersion;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (Info_Builder*) setTimestamp:(int64_t) value;
- (Info_Builder*) clearTimestamp;

- (BOOL) hasChangeset;
- (int64_t) changeset;
- (Info_Builder*) setChangeset:(int64_t) value;
- (Info_Builder*) clearChangeset;

- (BOOL) hasUid;
- (int32_t) uid;
- (Info_Builder*) setUid:(int32_t) value;
- (Info_Builder*) clearUid;

- (BOOL) hasUserSid;
- (int32_t) userSid;
- (Info_Builder*) setUserSid:(int32_t) value;
- (Info_Builder*) clearUserSid;

- (BOOL) hasVisible;
- (BOOL) visible;
- (Info_Builder*) setVisible:(BOOL) value;
- (Info_Builder*) clearVisible;
@end

@interface DenseInfo : PBGeneratedMessage {
@private
  NSMutableArray* mutableVisibleList;
  int32_t visibleMemoizedSerializedSize;
  NSMutableArray* mutableVersionList;
  int32_t versionMemoizedSerializedSize;
  NSMutableArray* mutableUidList;
  int32_t uidMemoizedSerializedSize;
  NSMutableArray* mutableUserSidList;
  int32_t userSidMemoizedSerializedSize;
  NSMutableArray* mutableTimestampList;
  int32_t timestampMemoizedSerializedSize;
  NSMutableArray* mutableChangesetList;
  int32_t changesetMemoizedSerializedSize;
}
- (NSArray*) versionList;
- (int32_t) versionAtIndex:(int32_t) index;
- (NSArray*) timestampList;
- (int64_t) timestampAtIndex:(int32_t) index;
- (NSArray*) changesetList;
- (int64_t) changesetAtIndex:(int32_t) index;
- (NSArray*) uidList;
- (int32_t) uidAtIndex:(int32_t) index;
- (NSArray*) userSidList;
- (int32_t) userSidAtIndex:(int32_t) index;
- (NSArray*) visibleList;
- (BOOL) visibleAtIndex:(int32_t) index;

+ (DenseInfo*) defaultInstance;
- (DenseInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DenseInfo_Builder*) builder;
+ (DenseInfo_Builder*) builder;
+ (DenseInfo_Builder*) builderWithPrototype:(DenseInfo*) prototype;

+ (DenseInfo*) parseFromData:(NSData*) data;
+ (DenseInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DenseInfo*) parseFromInputStream:(NSInputStream*) input;
+ (DenseInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DenseInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DenseInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DenseInfo_Builder : PBGeneratedMessage_Builder {
@private
  DenseInfo* result;
}

- (DenseInfo*) defaultInstance;

- (DenseInfo_Builder*) clear;
- (DenseInfo_Builder*) clone;

- (DenseInfo*) build;
- (DenseInfo*) buildPartial;

- (DenseInfo_Builder*) mergeFrom:(DenseInfo*) other;
- (DenseInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DenseInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) versionList;
- (int32_t) versionAtIndex:(int32_t) index;
- (DenseInfo_Builder*) replaceVersionAtIndex:(int32_t) index with:(int32_t) value;
- (DenseInfo_Builder*) addVersion:(int32_t) value;
- (DenseInfo_Builder*) addAllVersion:(NSArray*) values;
- (DenseInfo_Builder*) clearVersionList;

- (NSArray*) timestampList;
- (int64_t) timestampAtIndex:(int32_t) index;
- (DenseInfo_Builder*) replaceTimestampAtIndex:(int32_t) index with:(int64_t) value;
- (DenseInfo_Builder*) addTimestamp:(int64_t) value;
- (DenseInfo_Builder*) addAllTimestamp:(NSArray*) values;
- (DenseInfo_Builder*) clearTimestampList;

- (NSArray*) changesetList;
- (int64_t) changesetAtIndex:(int32_t) index;
- (DenseInfo_Builder*) replaceChangesetAtIndex:(int32_t) index with:(int64_t) value;
- (DenseInfo_Builder*) addChangeset:(int64_t) value;
- (DenseInfo_Builder*) addAllChangeset:(NSArray*) values;
- (DenseInfo_Builder*) clearChangesetList;

- (NSArray*) uidList;
- (int32_t) uidAtIndex:(int32_t) index;
- (DenseInfo_Builder*) replaceUidAtIndex:(int32_t) index with:(int32_t) value;
- (DenseInfo_Builder*) addUid:(int32_t) value;
- (DenseInfo_Builder*) addAllUid:(NSArray*) values;
- (DenseInfo_Builder*) clearUidList;

- (NSArray*) userSidList;
- (int32_t) userSidAtIndex:(int32_t) index;
- (DenseInfo_Builder*) replaceUserSidAtIndex:(int32_t) index with:(int32_t) value;
- (DenseInfo_Builder*) addUserSid:(int32_t) value;
- (DenseInfo_Builder*) addAllUserSid:(NSArray*) values;
- (DenseInfo_Builder*) clearUserSidList;

- (NSArray*) visibleList;
- (BOOL) visibleAtIndex:(int32_t) index;
- (DenseInfo_Builder*) replaceVisibleAtIndex:(int32_t) index with:(BOOL) value;
- (DenseInfo_Builder*) addVisible:(BOOL) value;
- (DenseInfo_Builder*) addAllVisible:(NSArray*) values;
- (DenseInfo_Builder*) clearVisibleList;
@end

@interface ChangeSet : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  int64_t id;
}
- (BOOL) hasId;
@property (readonly) int64_t id;

+ (ChangeSet*) defaultInstance;
- (ChangeSet*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChangeSet_Builder*) builder;
+ (ChangeSet_Builder*) builder;
+ (ChangeSet_Builder*) builderWithPrototype:(ChangeSet*) prototype;

+ (ChangeSet*) parseFromData:(NSData*) data;
+ (ChangeSet*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangeSet*) parseFromInputStream:(NSInputStream*) input;
+ (ChangeSet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangeSet*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChangeSet*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChangeSet_Builder : PBGeneratedMessage_Builder {
@private
  ChangeSet* result;
}

- (ChangeSet*) defaultInstance;

- (ChangeSet_Builder*) clear;
- (ChangeSet_Builder*) clone;

- (ChangeSet*) build;
- (ChangeSet*) buildPartial;

- (ChangeSet_Builder*) mergeFrom:(ChangeSet*) other;
- (ChangeSet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChangeSet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int64_t) id;
- (ChangeSet_Builder*) setId:(int64_t) value;
- (ChangeSet_Builder*) clearId;
@end

@interface Node : PBGeneratedMessage {
@private
  BOOL hasInfo_:1;
  BOOL hasId_:1;
  BOOL hasLat_:1;
  BOOL hasLon_:1;
  Info* info;
  int64_t id;
  int64_t lat;
  int64_t lon;
  NSMutableArray* mutableKeysList;
  int32_t keysMemoizedSerializedSize;
  NSMutableArray* mutableValsList;
  int32_t valsMemoizedSerializedSize;
}
- (BOOL) hasId;
- (BOOL) hasInfo;
- (BOOL) hasLat;
- (BOOL) hasLon;
@property (readonly) int64_t id;
@property (readonly, retain) Info* info;
@property (readonly) int64_t lat;
@property (readonly) int64_t lon;
- (NSArray*) keysList;
- (int32_t) keysAtIndex:(int32_t) index;
- (NSArray*) valsList;
- (int32_t) valsAtIndex:(int32_t) index;

+ (Node*) defaultInstance;
- (Node*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Node_Builder*) builder;
+ (Node_Builder*) builder;
+ (Node_Builder*) builderWithPrototype:(Node*) prototype;

+ (Node*) parseFromData:(NSData*) data;
+ (Node*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Node*) parseFromInputStream:(NSInputStream*) input;
+ (Node*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Node*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Node*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Node_Builder : PBGeneratedMessage_Builder {
@private
  Node* result;
}

- (Node*) defaultInstance;

- (Node_Builder*) clear;
- (Node_Builder*) clone;

- (Node*) build;
- (Node*) buildPartial;

- (Node_Builder*) mergeFrom:(Node*) other;
- (Node_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Node_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int64_t) id;
- (Node_Builder*) setId:(int64_t) value;
- (Node_Builder*) clearId;

- (NSArray*) keysList;
- (int32_t) keysAtIndex:(int32_t) index;
- (Node_Builder*) replaceKeysAtIndex:(int32_t) index with:(int32_t) value;
- (Node_Builder*) addKeys:(int32_t) value;
- (Node_Builder*) addAllKeys:(NSArray*) values;
- (Node_Builder*) clearKeysList;

- (NSArray*) valsList;
- (int32_t) valsAtIndex:(int32_t) index;
- (Node_Builder*) replaceValsAtIndex:(int32_t) index with:(int32_t) value;
- (Node_Builder*) addVals:(int32_t) value;
- (Node_Builder*) addAllVals:(NSArray*) values;
- (Node_Builder*) clearValsList;

- (BOOL) hasInfo;
- (Info*) info;
- (Node_Builder*) setInfo:(Info*) value;
- (Node_Builder*) setInfoBuilder:(Info_Builder*) builderForValue;
- (Node_Builder*) mergeInfo:(Info*) value;
- (Node_Builder*) clearInfo;

- (BOOL) hasLat;
- (int64_t) lat;
- (Node_Builder*) setLat:(int64_t) value;
- (Node_Builder*) clearLat;

- (BOOL) hasLon;
- (int64_t) lon;
- (Node_Builder*) setLon:(int64_t) value;
- (Node_Builder*) clearLon;
@end

@interface DenseNodes : PBGeneratedMessage {
@private
  BOOL hasDenseinfo_:1;
  DenseInfo* denseinfo;
  NSMutableArray* mutableKeysValsList;
  int32_t keysValsMemoizedSerializedSize;
  NSMutableArray* mutableIdList;
  int32_t idMemoizedSerializedSize;
  NSMutableArray* mutableLatList;
  int32_t latMemoizedSerializedSize;
  NSMutableArray* mutableLonList;
  int32_t lonMemoizedSerializedSize;
}
- (BOOL) hasDenseinfo;
@property (readonly, retain) DenseInfo* denseinfo;
- (NSArray*) idList;
- (int64_t) idAtIndex:(int32_t) index;
- (NSArray*) latList;
- (int64_t) latAtIndex:(int32_t) index;
- (NSArray*) lonList;
- (int64_t) lonAtIndex:(int32_t) index;
- (NSArray*) keysValsList;
- (int32_t) keysValsAtIndex:(int32_t) index;

+ (DenseNodes*) defaultInstance;
- (DenseNodes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DenseNodes_Builder*) builder;
+ (DenseNodes_Builder*) builder;
+ (DenseNodes_Builder*) builderWithPrototype:(DenseNodes*) prototype;

+ (DenseNodes*) parseFromData:(NSData*) data;
+ (DenseNodes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DenseNodes*) parseFromInputStream:(NSInputStream*) input;
+ (DenseNodes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DenseNodes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DenseNodes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DenseNodes_Builder : PBGeneratedMessage_Builder {
@private
  DenseNodes* result;
}

- (DenseNodes*) defaultInstance;

- (DenseNodes_Builder*) clear;
- (DenseNodes_Builder*) clone;

- (DenseNodes*) build;
- (DenseNodes*) buildPartial;

- (DenseNodes_Builder*) mergeFrom:(DenseNodes*) other;
- (DenseNodes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DenseNodes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) idList;
- (int64_t) idAtIndex:(int32_t) index;
- (DenseNodes_Builder*) replaceIdAtIndex:(int32_t) index with:(int64_t) value;
- (DenseNodes_Builder*) addId:(int64_t) value;
- (DenseNodes_Builder*) addAllId:(NSArray*) values;
- (DenseNodes_Builder*) clearIdList;

- (BOOL) hasDenseinfo;
- (DenseInfo*) denseinfo;
- (DenseNodes_Builder*) setDenseinfo:(DenseInfo*) value;
- (DenseNodes_Builder*) setDenseinfoBuilder:(DenseInfo_Builder*) builderForValue;
- (DenseNodes_Builder*) mergeDenseinfo:(DenseInfo*) value;
- (DenseNodes_Builder*) clearDenseinfo;

- (NSArray*) latList;
- (int64_t) latAtIndex:(int32_t) index;
- (DenseNodes_Builder*) replaceLatAtIndex:(int32_t) index with:(int64_t) value;
- (DenseNodes_Builder*) addLat:(int64_t) value;
- (DenseNodes_Builder*) addAllLat:(NSArray*) values;
- (DenseNodes_Builder*) clearLatList;

- (NSArray*) lonList;
- (int64_t) lonAtIndex:(int32_t) index;
- (DenseNodes_Builder*) replaceLonAtIndex:(int32_t) index with:(int64_t) value;
- (DenseNodes_Builder*) addLon:(int64_t) value;
- (DenseNodes_Builder*) addAllLon:(NSArray*) values;
- (DenseNodes_Builder*) clearLonList;

- (NSArray*) keysValsList;
- (int32_t) keysValsAtIndex:(int32_t) index;
- (DenseNodes_Builder*) replaceKeysValsAtIndex:(int32_t) index with:(int32_t) value;
- (DenseNodes_Builder*) addKeysVals:(int32_t) value;
- (DenseNodes_Builder*) addAllKeysVals:(NSArray*) values;
- (DenseNodes_Builder*) clearKeysValsList;
@end

@interface Way : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasInfo_:1;
  int64_t id;
  Info* info;
  NSMutableArray* mutableKeysList;
  int32_t keysMemoizedSerializedSize;
  NSMutableArray* mutableValsList;
  int32_t valsMemoizedSerializedSize;
  NSMutableArray* mutableRefsList;
  int32_t refsMemoizedSerializedSize;
}
- (BOOL) hasId;
- (BOOL) hasInfo;
@property (readonly) int64_t id;
@property (readonly, retain) Info* info;
- (NSArray*) keysList;
- (int32_t) keysAtIndex:(int32_t) index;
- (NSArray*) valsList;
- (int32_t) valsAtIndex:(int32_t) index;
- (NSArray*) refsList;
- (int64_t) refsAtIndex:(int32_t) index;

+ (Way*) defaultInstance;
- (Way*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Way_Builder*) builder;
+ (Way_Builder*) builder;
+ (Way_Builder*) builderWithPrototype:(Way*) prototype;

+ (Way*) parseFromData:(NSData*) data;
+ (Way*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Way*) parseFromInputStream:(NSInputStream*) input;
+ (Way*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Way*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Way*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Way_Builder : PBGeneratedMessage_Builder {
@private
  Way* result;
}

- (Way*) defaultInstance;

- (Way_Builder*) clear;
- (Way_Builder*) clone;

- (Way*) build;
- (Way*) buildPartial;

- (Way_Builder*) mergeFrom:(Way*) other;
- (Way_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Way_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int64_t) id;
- (Way_Builder*) setId:(int64_t) value;
- (Way_Builder*) clearId;

- (NSArray*) keysList;
- (int32_t) keysAtIndex:(int32_t) index;
- (Way_Builder*) replaceKeysAtIndex:(int32_t) index with:(int32_t) value;
- (Way_Builder*) addKeys:(int32_t) value;
- (Way_Builder*) addAllKeys:(NSArray*) values;
- (Way_Builder*) clearKeysList;

- (NSArray*) valsList;
- (int32_t) valsAtIndex:(int32_t) index;
- (Way_Builder*) replaceValsAtIndex:(int32_t) index with:(int32_t) value;
- (Way_Builder*) addVals:(int32_t) value;
- (Way_Builder*) addAllVals:(NSArray*) values;
- (Way_Builder*) clearValsList;

- (BOOL) hasInfo;
- (Info*) info;
- (Way_Builder*) setInfo:(Info*) value;
- (Way_Builder*) setInfoBuilder:(Info_Builder*) builderForValue;
- (Way_Builder*) mergeInfo:(Info*) value;
- (Way_Builder*) clearInfo;

- (NSArray*) refsList;
- (int64_t) refsAtIndex:(int32_t) index;
- (Way_Builder*) replaceRefsAtIndex:(int32_t) index with:(int64_t) value;
- (Way_Builder*) addRefs:(int64_t) value;
- (Way_Builder*) addAllRefs:(NSArray*) values;
- (Way_Builder*) clearRefsList;
@end

@interface Relation : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasInfo_:1;
  int64_t id;
  Info* info;
  NSMutableArray* mutableRolesSidList;
  int32_t rolesSidMemoizedSerializedSize;
  NSMutableArray* mutableKeysList;
  int32_t keysMemoizedSerializedSize;
  NSMutableArray* mutableValsList;
  int32_t valsMemoizedSerializedSize;
  NSMutableArray* mutableTypesList;
  int32_t typesMemoizedSerializedSize;
  NSMutableArray* mutableMemidsList;
  int32_t memidsMemoizedSerializedSize;
}
- (BOOL) hasId;
- (BOOL) hasInfo;
@property (readonly) int64_t id;
@property (readonly, retain) Info* info;
- (NSArray*) keysList;
- (int32_t) keysAtIndex:(int32_t) index;
- (NSArray*) valsList;
- (int32_t) valsAtIndex:(int32_t) index;
- (NSArray*) rolesSidList;
- (int32_t) rolesSidAtIndex:(int32_t) index;
- (NSArray*) memidsList;
- (int64_t) memidsAtIndex:(int32_t) index;
- (NSArray*) typesList;
- (Relation_MemberType) typesAtIndex:(int32_t) index;

+ (Relation*) defaultInstance;
- (Relation*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Relation_Builder*) builder;
+ (Relation_Builder*) builder;
+ (Relation_Builder*) builderWithPrototype:(Relation*) prototype;

+ (Relation*) parseFromData:(NSData*) data;
+ (Relation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Relation*) parseFromInputStream:(NSInputStream*) input;
+ (Relation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Relation*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Relation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Relation_Builder : PBGeneratedMessage_Builder {
@private
  Relation* result;
}

- (Relation*) defaultInstance;

- (Relation_Builder*) clear;
- (Relation_Builder*) clone;

- (Relation*) build;
- (Relation*) buildPartial;

- (Relation_Builder*) mergeFrom:(Relation*) other;
- (Relation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Relation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int64_t) id;
- (Relation_Builder*) setId:(int64_t) value;
- (Relation_Builder*) clearId;

- (NSArray*) keysList;
- (int32_t) keysAtIndex:(int32_t) index;
- (Relation_Builder*) replaceKeysAtIndex:(int32_t) index with:(int32_t) value;
- (Relation_Builder*) addKeys:(int32_t) value;
- (Relation_Builder*) addAllKeys:(NSArray*) values;
- (Relation_Builder*) clearKeysList;

- (NSArray*) valsList;
- (int32_t) valsAtIndex:(int32_t) index;
- (Relation_Builder*) replaceValsAtIndex:(int32_t) index with:(int32_t) value;
- (Relation_Builder*) addVals:(int32_t) value;
- (Relation_Builder*) addAllVals:(NSArray*) values;
- (Relation_Builder*) clearValsList;

- (BOOL) hasInfo;
- (Info*) info;
- (Relation_Builder*) setInfo:(Info*) value;
- (Relation_Builder*) setInfoBuilder:(Info_Builder*) builderForValue;
- (Relation_Builder*) mergeInfo:(Info*) value;
- (Relation_Builder*) clearInfo;

- (NSArray*) rolesSidList;
- (int32_t) rolesSidAtIndex:(int32_t) index;
- (Relation_Builder*) replaceRolesSidAtIndex:(int32_t) index with:(int32_t) value;
- (Relation_Builder*) addRolesSid:(int32_t) value;
- (Relation_Builder*) addAllRolesSid:(NSArray*) values;
- (Relation_Builder*) clearRolesSidList;

- (NSArray*) memidsList;
- (int64_t) memidsAtIndex:(int32_t) index;
- (Relation_Builder*) replaceMemidsAtIndex:(int32_t) index with:(int64_t) value;
- (Relation_Builder*) addMemids:(int64_t) value;
- (Relation_Builder*) addAllMemids:(NSArray*) values;
- (Relation_Builder*) clearMemidsList;

- (NSArray*) typesList;
- (Relation_MemberType) typesAtIndex:(int32_t) index;
- (Relation_Builder*) replaceTypesAtIndex:(int32_t) index with:(Relation_MemberType) value;
- (Relation_Builder*) addTypes:(Relation_MemberType) value;
- (Relation_Builder*) addAllTypes:(NSArray*) values;
- (Relation_Builder*) clearTypesList;
@end

